name: Dependabot Automerge
author: Anthony McLin
description: automatically merge pull requests created by Dependabot

runs:
  using: composite

  strategy:
    matrix:
      pr-title-prefixes: ['chore(deps-dev):']

  steps:
    - name: Automerge Dependabot Pull Requests
      description: Merging pull request prefixed with ${{ matrix.pr-title-prefixes }}
      uses: ridedott/merge-me-action@v2
      if: |
        github.actor == 'dependabot[bot]' &&
        github.event_name == 'pull_request' &&
        startsWith(github.event.pull_request.title, ${{ matrix.pr-title-prefixes }})
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
