# This workflow will run tests using node and then publish a package to GitHub Packages when a successful unit test
# has been run on main.
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release

on:
  workflow_run:
    workflows: ['Tests']
    branches: [main]
    types:
      - completed
  # workflow_dispatch: # allow to manually start the workflow
  # this is diabled because there is an explicit check for completion of
  # the test workflow below

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: HUSKY=0 npm ci
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  # publish-gpr:
  #   name: Release to GitHub Packages
  #   needs: releas
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 12
  #         registry-url: https://npm.pkg.github.com/
  #     - run: npm ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
